import React, { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Clock3, Mail, MapPin, Menu, MessageCircle, PackageCheck, Phone, Quote, Send, ShieldCheck, Truck, Users, X } from 'lucide-react';
import heroImage from '../Images/hero-transport.jpg';
import aboutImage from '../Images/about-containers.jpg';
import servicePort from '../Images/service-port.jpg';
import serviceLogistics from '../Images/service-logistics.jpg';
import serviceShip from '../Images/service-ship.jpg';
import testimonialBg from '../Images/testimonial-bg.jpg';
import callbackBg from '../Images/callback-bg.jpg';
import mapImage from '../Images/map.jpg';
import Navbar from '../Components/Navbar';

const nav = ['Home','About us','Services','Jobs','News','Contacts'];
const reasons = [
 {icon: ShieldCheck,title:'Supply Chain Solutions',text:'Reliable planning, sourcing and freight coordination built around your business.'},
 {icon: Truck,title:'End-to-End Transportation',text:'One connected logistics flow from origin to final delivery, with clear visibility.'},
 {icon: PackageCheck,title:'Contract Logistics',text:'Flexible warehousing and distribution solutions designed for long-term growth.'}
];
const services = [
 {image:servicePort,n:'01',title:'Quality management system',text:'Consistent processes and careful cargo handling at every stage.'},
 {image:serviceLogistics,n:'02',title:'E-commerce logistics solution',text:'Fast fulfillment and delivery support for modern online businesses.'},
 {image:serviceShip,n:'03',title:'Logistics & Aftermarket logistics',text:'Flexible solutions that keep products moving beyond the first delivery.'}
];
const safety = [
 ['Integrity properties','We work with transparency and dependable service standards.'],['Long-sightedness','Long-term planning keeps your logistics ready for tomorrow.'],['Challenging staff','Experienced people solve complex logistics challenges.'],['Privacy and safety','Your business information and cargo are treated with care.'],['Quality services','Practical logistics support focused on measurable results.'],['Continuous','We improve processes continuously to keep operations efficient.'],['Innovation solutions','Smarter tools and ideas help simplify your supply chain.'],['Operational excellence','Disciplined execution keeps every shipment on track.']
];
function Logo({light=false}){return <div className={`flex items-center gap-2 ${light?'text-white':'text-[#062d43]'}`}><div className="relative grid h-8 w-8 place-items-center"><span className="absolute h-6 w-6 rotate-45 rounded-[5px] border-[3px] border-[#f39b23]"/><span className="absolute h-3.5 w-3.5 rounded-full bg-[#f39b23]"/></div><div className="leading-none"><div className="text-[11px] font-black tracking-[.14em]">AAMAR</div><div className="text-[11px] font-black tracking-[.09em]">AL WATHEQ</div><div className="mt-1 text-[6px] tracking-[.18em] opacity-60">IMPORT • EXPORT • LOGISTICS</div></div></div>}
function Title({children,center=false,eyebrow}){return <div className={center?'mx-auto max-w-2xl text-center':'max-w-xl'}>{eyebrow&&<div className="mb-3 text-[10px] font-bold uppercase tracking-[.24em] text-[#f39b23]">{eyebrow}</div>}<h2 className="text-3xl font-semibold tracking-[-.035em] text-[#082f44] md:text-[40px]">{children}</h2><div className={`mt-4 h-[2px] w-12 bg-[#f39b23] ${center?'mx-auto':''}`}/></div>}
function Btn({children}){return <button className="inline-flex items-center justify-center gap-2 bg-[#f39b23] px-6 py-3 text-[10px] font-bold uppercase tracking-[.08em] text-white transition hover:bg-[#e48710]">{children}<ArrowRight size={14}/></button>}

export default function ImportExport(){
 const [open,setOpen]=useState(false); const [sent,setSent]=useState(false); const [slide,setSlide]=useState(0);
 return <div className="min-h-screen bg-white font-sans text-[#173445]">
<Navbar/>

  <section id="home" className="overflow-hidden bg-[#eaf1f3]"><div className="mx-auto grid max-w-[1180px] md:min-h-[520px] md:grid-cols-[.95fr_1.05fr]"><div className="relative z-10 flex flex-col justify-center px-6 py-16 sm:px-10 md:px-12 lg:px-16"><div className="mb-4 text-[10px] font-bold uppercase tracking-[.25em] text-[#f39b23]">Aamar Al Watheq</div><h1 className="max-w-[560px] text-[38px] font-extrabold uppercase leading-[.98] tracking-[-.04em] text-[#062d43] sm:text-5xl md:text-[48px]">Connect your business to a world of possibilities</h1><p className="mt-6 max-w-[470px] text-xs leading-6 text-[#49606c]">A dependable import, export and logistics partner connecting businesses with efficient transportation, cargo handling and supply-chain solutions.</p><div className="mt-7"><Btn>View services</Btn></div></div><div className="relative min-h-[330px] overflow-hidden md:min-h-full"><img src={heroImage} alt="Cargo ship, containers, truck and aircraft" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#eaf1f3] via-transparent to-transparent md:w-1/3"/></div></div></section>

  <section className="bg-[#f6f6f5] px-5 py-14 md:py-16"><div className="mx-auto max-w-[960px]"><Title center>Why traders choose us</Title><div className="mt-10 grid gap-4 md:grid-cols-3">{reasons.map(({icon:Icon,title,text})=><article key={title} className="border border-[#e6e8e7] bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><div className="mb-5 grid h-9 w-9 place-items-center rounded-full bg-[#fff4e4] text-[#f39b23]"><Icon size={17}/></div><h3 className="text-sm font-bold text-[#082f44]">{title}</h3><p className="mt-3 text-[10px] leading-5 text-[#71808a]">{text}</p><a href="#services" className="mt-5 inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider">Read more <ArrowUpRight size={12}/></a></article>)}</div></div></section>

  <section id="about-us" className="bg-white px-5 py-16 md:py-24"><div className="mx-auto grid max-w-[960px] items-center gap-12 md:grid-cols-2 md:gap-20"><div className="relative"><img src={aboutImage} alt="Container logistics and business meeting" className="h-[350px] w-full object-cover sm:h-[410px]"/><div className="absolute left-5 top-5 bg-white/95 px-4 py-3 shadow-lg"><div className="text-2xl font-black text-[#f39b23]">5+</div><div className="text-[9px] font-bold uppercase leading-3 tracking-wider">years of<br/>experience</div></div></div><div><Title eyebrow="Who we are">About us</Title><h3 className="mt-7 text-sm font-bold leading-5">Above all, we believe that real change is possible and that tomorrow doesn't have to be like today.</h3><p className="mt-4 text-[11px] leading-6 text-[#73818a]">Successful logistics requires leaders, partners and teams who understand how business, transportation, trade and technology connect. We build practical solutions around the needs of every shipment and every client.</p><div className="mt-7"><Btn>Read more</Btn></div></div></div></section>

  <section id="services" className="bg-[#062d43]"><div className="mx-auto grid max-w-[1180px] md:grid-cols-3">{services.map(s=><article key={s.n} className="group relative min-h-[390px] overflow-hidden border-b border-white/10 md:min-h-[470px] md:border-b-0 md:border-r last:border-r-0"><img src={s.image} alt={s.title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#031b29] via-[#062d43]/10 to-transparent"/><div className="absolute bottom-0 p-7 text-white"><div className="text-[10px] font-bold text-[#f39b23]">{s.n}</div><h3 className="mt-2 max-w-[220px] text-lg font-semibold leading-tight">{s.title}</h3><p className="mt-3 max-w-[245px] text-[10px] leading-5 text-white/75">{s.text}</p><a href="#callback" className="mt-5 grid h-8 w-8 place-items-center rounded-full border border-white/30 bg-white/10 hover:bg-[#f39b23]"><ArrowRight size={13}/></a></div></article>)}</div></section>

  <section className="bg-white px-5 py-16 md:py-20"><div className="mx-auto max-w-[960px]"><Title center>Your cargo is safe with us</Title><div className="mt-10 grid gap-x-8 gap-y-8 sm:grid-cols-2 lg:grid-cols-4">{safety.map(([t,p],i)=><div key={t} className="flex gap-3"><div className="mt-0.5 shrink-0 text-[#f39b23]">{i%4===0?<ShieldCheck size={22}/>:i%4===1?<Clock3 size={22}/>:i%4===2?<Users size={22}/>:<PackageCheck size={22}/>}</div><div><h3 className="text-[11px] font-bold">{t}</h3><p className="mt-2 text-[9px] leading-4 text-[#89949a]">{p}</p></div></div>)}</div></div></section>

  <section className="relative overflow-hidden bg-[#062d43]"><img src={testimonialBg} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-[#062d43]/70"/><div className="relative mx-auto grid max-w-[960px] items-center gap-10 px-5 py-16 md:grid-cols-[.65fr_1fr] md:py-20"><div className="text-white"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-[#f39b23]">Testimonials</div><h2 className="mt-3 text-3xl font-semibold leading-tight">What they say<br/>about us</h2><p className="mt-4 text-[10px] text-white/60">Trusted by businesses that move across borders.</p></div><div className="relative bg-white p-7 shadow-2xl sm:p-9"><Quote className="absolute -left-3 -top-4 fill-[#f39b23] text-[#f39b23]" size={36}/><p className="text-sm leading-6 text-[#4e626d]">“Reliable communication, careful coordination and a team that understands the pressure behind every shipment. Aamar Al Watheq makes complex logistics feel straightforward.”</p><div className="mt-6 flex items-end justify-between border-t border-black/10 pt-5"><div><div className="text-[11px] font-bold">Cameron Williamson</div><div className="mt-1 text-[9px] text-[#8b969c]">Commercial Partner</div></div><div className="flex gap-2"><button disabled={slide===0} onClick={()=>setSlide(0)} className="grid h-7 w-7 place-items-center border border-black/10"><ChevronLeft size={13}/></button><button disabled={slide===1} onClick={()=>setSlide(1)} className="grid h-7 w-7 place-items-center border border-black/10"><ChevronRight size={13}/></button></div></div></div></div></section>

  <section className="bg-white px-5 py-12 md:py-16"><Title center>Our partners</Title><div className="mx-auto mt-9 flex max-w-[850px] flex-wrap items-center justify-center gap-x-12 gap-y-6 opacity-35">{['CARAVAN','GLOBAL','CARGO','TRADE','CHAIN'].map(w=><div key={w} className="flex items-center gap-1 text-[#52636c]"><div className="h-5 w-5 rotate-45 border-2 border-current"/><span className="text-[9px] font-black tracking-[.12em]">{w}<span className="block text-[5px] tracking-[.2em]">PARTNER</span></span></div>)}</div></section>

  <section id="callback" className="relative overflow-hidden bg-[#062d43] px-5 py-12" style={{backgroundImage:`linear-gradient(rgba(3,29,43,.82),rgba(3,29,43,.82)),url(${callbackBg})`,backgroundSize:'cover',backgroundPosition:'center'}}><div className="relative mx-auto max-w-[960px]"><div className="text-center"><h2 className="text-3xl font-semibold text-white md:text-[40px]">Request a call back</h2><div className="mx-auto mt-4 h-[2px] w-12 bg-[#f39b23]"/></div><form onSubmit={e=>{e.preventDefault();setSent(true)}} className="mt-8 grid gap-3 sm:grid-cols-3 lg:grid-cols-[1fr_1fr_1fr_auto]"><input required placeholder="First name" className="h-11 bg-white px-4 text-[10px] outline-none"/><select required defaultValue="" className="h-11 bg-white px-4 text-[10px] outline-none"><option value="" disabled>Business planning</option><option>Import</option><option>Export</option><option>Freight</option><option>Warehousing</option></select><input required placeholder="Phone number" className="h-11 bg-white px-4 text-[10px] outline-none"/><button className="h-11 bg-[#f39b23] px-7 text-[10px] font-bold uppercase tracking-wider text-white">Submit</button></form>{sent&&<div className="mt-4 flex items-center justify-center gap-2 text-[10px] text-white"><Check size={14} className="text-[#f39b23]"/> Thank you — your callback request has been received.</div>}</div></section>

  <section className="relative h-[330px] overflow-hidden bg-[#e5e1d8]"><img src={mapImage} alt="Map showing service area" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute left-1/2 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-[#f39b23] text-white shadow-xl"><MapPin size={22}/></div><div className="absolute bottom-5 left-5 bg-white/95 p-4 shadow-lg sm:left-8"><div className="text-[9px] font-bold uppercase tracking-wider text-[#f39b23]">Aamar Al Watheq</div><div className="mt-1 text-xs font-semibold">Islamabad • Pakistan</div></div></section>

  <footer className="bg-[#03263a] text-white"><div className="mx-auto grid max-w-[1180px] gap-10 px-6 py-14 md:grid-cols-[1.35fr_.75fr_1fr_1fr]"><div><Logo light/><p className="mt-6 max-w-xs text-[10px] leading-5 text-white/55">Aamar Al Watheq connects businesses with dependable import, export, transportation and logistics support.</p><div className="mt-5 flex gap-2"></div></div><div><h3 className="text-[10px] font-bold uppercase tracking-wider">Navigation</h3><div className="mt-5 flex flex-col gap-3 text-[10px] text-white/55">{nav.map(x=><a key={x} href={'#'+x.toLowerCase().replaceAll(' ','-')} className="hover:text-[#f39b23]">{x}</a>)}</div></div><div><h3 className="text-[10px] font-bold uppercase tracking-wider">Get in touch</h3><div className="mt-5 flex flex-col gap-4 text-[10px] text-white/55"><span className="flex gap-3"><MapPin size={13} className="text-[#f39b23]"/>Islamabad, Pakistan</span><span className="flex gap-3"><Phone size={13} className="text-[#f39b23]"/>+92 51 000 0000</span><span className="flex gap-3"><Mail size={13} className="text-[#f39b23]"/>contact@aamaralwatheq.com</span></div></div><div><h3 className="text-[10px] font-bold uppercase tracking-wider">Sign up for email alerts</h3><p className="mt-5 text-[10px] leading-5 text-white/55">Receive company news, logistics updates and service information.</p><div className="mt-4 flex h-9"><input placeholder="Enter your e-mail" className="min-w-0 flex-1 bg-white px-3 text-[9px] text-[#173445] outline-none"/><button className="grid w-10 place-items-center bg-[#f39b23]"><Send size={13}/></button></div></div></div><div className="border-t border-white/10 px-6 py-5"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-2 text-[8px] text-white/35 sm:flex-row"><span>© {new Date().getFullYear()} Aamar Al Watheq. All rights reserved.</span><span>Import • Export • Freight • Logistics</span></div></div></footer>
  <div className="fixed inset-x-0 bottom-0 z-50 flex border-t border-white/10 bg-[#062d43] p-2 lg:hidden"><a href="tel:+92510000000" className="flex flex-1 items-center justify-center gap-2 py-3 text-[10px] font-bold uppercase text-white"><Phone size={14}/>Call</a><a href="#callback" className="flex flex-1 items-center justify-center gap-2 bg-[#f39b23] py-3 text-[10px] font-bold uppercase text-white"><MessageCircle size={14}/>Request a call</a></div>
 </div>
}
